### ISSUE TITLE
Structure with multiple tags does not return data

### ISSUE THREAD

**Issue by whawkins2005** [Synergex/HarmonyCore#269]
I have a file that has 3 tag overlays determined by a record type field.  If the record type is zero or one, then structure layout A applies, if the record type is 2 then structure layout B applied and if the record type is 3 structure layout C applies.  There are appropriate tags setup on each structure layout.

when I codegen the odata access, I can get all records for layout B and C, but not A.  When I separated the two record types that match layout A into two separate structures each with a single tag value, the data is returned fine.

Seems that tags that say "field eq value1" or "field eq value2" on a single structure do not work as intended.

**Comment by whawkins2005** [comment]
Only works for multiple tags if all tags are AND tags.

**Comment by SteveIves** [comment]
I think that may be documented as a restriction somewhere.

Steve Ives

________________________________
From: whawkins2005 ***@***.***>
Sent: Friday, March 25, 2022 5:19:27 PM
To: Synergex/HarmonyCore ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] Re: [Synergex/HarmonyCore] Structure with multiple tags does not return data (Issue #269)


Only works for multiple tags if all tags are AND tags.

—
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSynergex%2FHarmonyCore%2Fissues%2F269%23issuecomment-1079530537&data=04%7C01%7Csteve.ives%40synergex.com%7C5edfc68a71a142c06e3c08da0ebe49fc%7Cf3ba08220f7241fcbc3b2f77b0cb52bd%7C0%7C0%7C637838507704586951%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=IRmgj%2BvbHuuuJD5W2jidQyqZFJw9NFOORvvSTpV%2F0qM%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAHUZIHBDT6V3UYEPKCZ7PTVBZJY7ANCNFSM5RSHH6HA&data=04%7C01%7Csteve.ives%40synergex.com%7C5edfc68a71a142c06e3c08da0ebe49fc%7Cf3ba08220f7241fcbc3b2f77b0cb52bd%7C0%7C0%7C637838507704596900%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=e6mZXQQAiwd7DhyIPwu45wac9nYwLmjSwfH9Fb3Gc6w%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

CAUTION: This email originated from outside of Synergex. Please do not click links or open attachments from an unknown or suspicious sender.
