### ISSUE TITLE
Can Harmony Core host non-Synergy web api controllers

### ISSUE THREAD

**Issue by erikread** [Synergex/HarmonyCore#291]
We want to use Harmony Core but utilize api controllers in referenced class libraries written in C# alongside those written in DBL.
If so, how?
In .NET 6 C# Web Api, simply referencing the class library in the hosting project makes it accessible.
This doesn't appear to work in Harmony Core (or I am doing something wrong)

Also, https://synergexresourcecenter.force.com/sitecase?id=5006Q00001uuK4EQAU

**Comment by hippiehunter** [comment]
What you're seeing with a C# hosting project is magic, If the dll containing the controllers happens to be loaded, then it will work. If its not otherwise loaded you can force the issue using AddApplicationPart. In the test project we demonstrate this here https://github.com/Synergex/HarmonyCore/blob/master/Services/Startup.dbl#L235

**Comment by erikread** [comment]
@hippiehunter  Thanks. That worked great
