### ISSUE TITLE
regen.bat error

### ISSUE THREAD

**Issue by erikread** [Synergex/HarmonyCore#292]
This might be a bug but we'll go with question first...
Attempting to set up TraditionalBridge using our SMC.

I have the following set in regen.bat
set ENABLE_XFSERVERPLUS_MIGRATION=YES
set SMC_XML_FILE=e:\weblib.xml

I used the following command to generate my smc xml:
dbl2xml -out=e:\weblib.xml C:\cdcompiler\Develop\CoreRelease2023\libraries\weblib\~weblib.web

After running regen I get the following output:
Generating Traditional Bridge code for interface weblib

Generating interface method stubs [Traditional]

Generating interface method dispatcher classes [Traditional]

Task complete, 1 file generated.

 - weblibMethodDispatchers.dbl

Generating interface dispatcher classes [Traditional]

Task complete, 1 file generated.

 - weblibDispatcher.dbl

Generating interface data model classes [Traditional]
ERROR: Method catalog export file contains no structures!

2 files are generated weblibDispatcher.dbl and weblibMethodDispatchers.dbl containing the methods needed.
When I go to compile, none of our repository structures are found.
For instance:

%DBL-E-NVTF, Cannot resolve type for field arg2 : arg2,               StrAbaLookupRq
TraditionalBridge
E:\dev\src\MyApi\TraditionalBridge\Dispatchers\weblibMethodDispatchers.dbl
451
We don't have a repository structure named StrAbaLookupRq but we do have one named ABA_LOOKUP_RQ so I assume some name mangling is going on but regardless, it isn't being found. How do we get our dispatchers to see our repository?

**Comment by SteveIves** [comment]
When you generated the code, data model and metadata classes should have been generated for the structure in the source\models folder. Do you see them> And have you added them to the project so they are built?

**Comment by erikread** [comment]
Nothing is generated in the folder you suggest.
Maybe we should focus on the first error from DBL2XML...
Generating interface data model classes [Traditional]
ERROR: Method catalog export file contains no structures!

Here is a snippet from the XML:   
 <method name="ABA_SEARCH_RC" id="ABA_SEARCH_RC" routine="ABA_SEARCH_RC" elb="LIB64:weblib">
      <param name="commonCoreInformation" type="structure" structureName="browser_connection_data" sfldname="browser_connection_data" size="321" dir="inout"/>
      <param name="abaLookupRQ" type="structure" structureName="aba_lookup_rq" sfldname="aba_lookup_rq" size="145"/>
      <param name="items" type="structure" structureName="xp_aba_file" sfldname="xp_aba_file" size="147" collection="System.ArrayList" dir="out"/>
    </method>
I have attached our regen.bat
I am using instructions found at:
https://github.com/Synergex/HarmonyCore/wiki/Tutorial-06-01-xfServerPlus-Migration

Also removed all OData generation from regen.bat
[regen.bat.zip](https://github.com/Synergex/HarmonyCore/files/9754001/regen.bat.zip)

**Comment by erikread** [comment]
So after manually getting things generated I am noticing a few things:
If the structure ends an s, it is dropped. Normally not an issue unless there is a field inside the structure with a non-pluralized name of the field.
Imbedded structures (groups) are causing a huge amount of errors because it prefixes the structure name to the field name making a very long field name (ComRejectPostingRecComRejTransactionAmount) where ComRejectPostingRec is the imbedded structure name. All of the fields of that structure start with the same prefixes so we have a dozen fields causing DBL-E-DUPSYP errors

**Comment by erikread** [comment]
One more interesting thing...
Even running codegen manually with -s *, I am only getting a subset of my repository structures. 
All structures starting with A-Jx (604 items)

I am now using the codegen flags -g f to stop prefixing the group name and -ncp to stop stripping ending s from structure names.

Is there a way to only include the group structure as a structure not as one big alpha field?

**Comment by SteveIves** [comment]
There is an option in regen.bat to turn off custom pluralization. Essentially it uses -ncp.

Not sure what impact using -g f will have; I don't think we have ever tested that. We do have plans for a better mechanism for groups, but it's not complete yet.

If you are using dbl2xml to load the method catalog, you need to then EXPORT the catalog to the XML file being used by CodeGen, That should add the necessary repository structures into the XML file and then the data models should get generated.

**Comment by erikread** [comment]
Do I need to do more than this (from the original post)?
dbl2xml -out=e:\weblib.xml C:\cdcompiler\Develop\CoreRelease2023\libraries\weblib~weblib.web

Why am I only getting 604 classes built (out of about 1500) when doing this?
codegen -s * -t TraditionalModel TraditionalMetadata -i E:\dev\src\MyApi\Templates\TraditionalBridge -o E:\dev\src\MyApi\TraditionalBridge\source\models -n TraditionalBridge.Models -lf -u E:\dev\src\MyApi\UserDefinedTokens.tkn -rps RPSFILP:RPSMAIN.ISM RPSFILP:RPSTEXT.ISM -r

**Comment by SteveIves** [comment]
The XML file created by DVL2XML only contains method and parameter information, no structures. Code generation from a method catalog requires an XML file that was EXPORTED by the method definition utility, because those files also include structure information. So, every time you run DBL2XML, you also need to subsequently run an mdu export (dbr DBLDIR:mdu -e ...) to export an XML file that COdeGen can use.

As to why you only get 604 classes of 1500 when you use -s * I'm not sure, we might need to meet to drill into that.

**Comment by erikread** [comment]
Thanks @SteveIves  that helped a lot and i've gotten further.
Next big headache.
All of our generated method dispatchers are failing compile with a %DBL-E-TYPPARM error.
For instance:
Error		%DBL-E-TYPPARM, Type mismatch for parameter 1 in routine ABA_SEARCH_RC : xcall ABA_SEARCH_RC(arg1,arg2,arg3)	TraditionalBridge	E:\dev\src\MyApi\TraditionalBridge\Dispatchers\weblibMethodDispatchers.dbl	197	
In the dispatcher, arg1 is defined as:
arg1,               StrBrowserConnectionData

and set:
arg1 = arg1DataObject.SynergyRecord

and used:
xcall ABA_SEARCH_RC(**arg1**,arg2,arg3)

That method is defined in the smc (xml version):
    <method name="ABA_SEARCH_RC" id="ABA_SEARCH_RC" routine="ABA_SEARCH_RC" elb="LIB64:weblib">
      **<param name="commonCoreInformation" type="structure" structureName="Browser_connection_data" dir="inout"/>**
      <param name="abaLookupRQ" type="structure" structureName="Aba_lookup_rq"/>
      <param name="items" type="structure" structureName="Xp_aba_file" dir="out" collection="System.ArrayList" size="147"/>
    </method>

And in the source as:
{xfMethod(intWeblib, elbmacro, name="ABA_SEARCH_RC")}
.subroutine ABA_SEARCH_RC
	
	{xfParameter(nameCCI)}
	**inout required a_remoteData	,browser_connection_data**
	
	{xfParameter(name="abaLookupRQ")}
	in   required    a_aba_lookup_rq            ,ABA_LOOKUP_RQ 

	{xfParameter(name="items", typeCol, structure="xp_aba_file")}
	out required a_RecordList	,@ArrayList
	
	endparams
	...
	
This is happening on all parameters expecting a structure

**Comment by erikread** [comment]
Thanks @SteveIves that helped a lot.
Now my issue is passing structures  from the dispatcher to the traditional synergy routine. They are failing with Type mismatch error.

**Comment by erikread** [comment]
**Will there be a TraditionalBridge tutorial discussing the use of repository structures?**
I have taken our application out of the mix and created a single repository structure, a single attributed method that I import into the smc and then export to xml. I then use codegen and I am running into the following issues:

- From the TraditionalBridgeHost.dbl source, dispatcher.Dispatch(ttchan) can't be found
- From the weblibMethodDispatcher.dbl a Type mismatch error for my repository structure when calling my elb routine.

**Comment by erikread** [comment]
@SteveIves Any idea when we might see a TraditionalBridge demo focusing on xfServerPlus migration utilizing repository structures?

**Comment by tscaff** [comment]
Hi Steve,

I have been working with Erik on the xfServerPlus migration options in the REGEN.BAT script as well.  I have encountered many of the same issues he is having.  It probably would help if we had a meeting and shared what we are seeing.  To list the current issues that he and I have seen,  here is the list from some of items.

1.  It appears the code generation is creating structure names prefixed with "str" as Erik described and turning around and generating method definitions without the "str" on them, per this error message in my build.

Severity	Code	Description	Project	File	Line	Suppression State
Error		%DBL-E-NVTP, Cannot resolve type for parameter controlSystem : required in    controlSystem, strBankControlSy	TraditionalBridge	C:\Dev\Src\corerelease2023\TomsWebApi\TraditionalBridge\Methods\weblibMethodStubs.dbl	431	

2. Appear to be getting some form of duplicate symbol compiler error.

Severity	Code	Description	Project	File	Line	Suppression State
Error		%DBL-E-DUPSYP, Duplicate symbol ComRejectPostingRecComRejTrans for same parent not allowed : public property ComRejectPostingRecComRejTransactionDate, d	TraditionalBridge	C:\Dev\Src\corerelease2023\TomsWebApi\TraditionalBridge\Models\BrowserEipRejectInfo.dbl	95	

3. Several undefined structure references.  Appears that the structure name is cutoff on the MethodStub generation.  We can provide multiple examples.

Severity	Code	Description	Project	File	Line	Suppression State
Error		%DBL-E-NVTP, Cannot resolve type for parameter XpCopyPassportCardRs : required out   XpCopyPassportCardRs, strXpCopyPassportCardR	TraditionalBridge	C:\Dev\Src\corerelease2023\TomsWebApi\TraditionalBridge\Methods\weblibMethodStubs.dbl	2309	

I could keep posting errors, but I think you get the point.  We have several build issues we need your help on in order to get the xfServerPlus Migration to be complete for us.  Any help would be great at this point.

Thank Steve.

**Comment by tscaff** [comment]
Hi Steve,

Per my previous post, I think maybe the pluralization being turned off is affecting structure names with the trailing 's' on it.  Like it is assuming that it needs to remove the 's' because pluralization is disabled(set NO_CUSTOM_PLURALIZATION=-ncp
) .  Is that possibly what is happening?

**Comment by hippiehunter** [comment]
closing this after migration to use the CLI tool instead of regen.bat
