### ISSUE TITLE
Authentication via custom code

### ISSUE THREAD

**Issue by SledgeEC** [Synergex/HarmonyCore#296]
I am attempting to create entity endpoints for our software by completing the tutorials but have run into an issue that I cannot figure out. I am trying to implement the changes in the 'authentication via custom code' section.

I have tried multiple times but keep getting the same error when I attempt to connect to the endpoint from postman. I am able to receive the token but when I send it to the protected endpoint I get a '500 Internal server error - System.InvalidOperationException : Endpoint Services.Controllers.RecordController.GetRecord contains authorization metadata, but a middleware was not found that supports authorization.' It goes on to state that different methods used in the generated code need to be called in a specific order but the code calls them differently than the error message prescribes and changing it does not make sense since it immediately gets overwritten if I change it.

I have tried looking here and elsewhere for info that might help me figure this out but have not had any luck. What am I missing or doing wrong?

**Comment by SteveIves** [comment]
What time zone are you in?

**Comment by SledgeEC** [comment]
I am located in PST.

**Comment by SteveIves** [comment]
OK, me too. I already wrapped up for the day, but if you’d like a brief get-together on a web meeting Monday or Tuesday, maybe I can spot the problem.

Steve Ives

________________________________
From: SledgeEC ***@***.***>
Sent: Friday, November 18, 2022 4:38:41 PM
To: Synergex/HarmonyCore ***@***.***>
Cc: Steve Ives ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [Synergex/HarmonyCore] Authentication via custom code (Issue #296)


I am located in PST.

—
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSynergex%2FHarmonyCore%2Fissues%2F296%23issuecomment-1320704911&data=05%7C01%7Csteve.ives%40synergex.com%7C400ea2672eed451e532108dac9c6683f%7Cf3ba08220f7241fcbc3b2f77b0cb52bd%7C0%7C0%7C638044151238490811%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=cFeJUi0cNFv%2FNGwUu38%2FjN%2FQQCiKlS0tgm6Kfz1y6Pk%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAHUZICLU6LSVMB67QPJMLLWJAORBANCNFSM6AAAAAASE7LTLQ&data=05%7C01%7Csteve.ives%40synergex.com%7C400ea2672eed451e532108dac9c6683f%7Cf3ba08220f7241fcbc3b2f77b0cb52bd%7C0%7C0%7C638044151238490811%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YLZlPI3E4E8%2FxevXVL9zczu7LGXW3qBxGHJ97cvdyTw%3D&reserved=0>.
You are receiving this because you commented.Message ID: ***@***.***>

CAUTION: This email originated from outside of Synergex. Please do not click links or open attachments from an unknown or suspicious sender.

**Comment by SledgeEC** [comment]
That would be great. I had a couple other questions I needed some direction on and was already planning on trying to make an appointment.

**Comment by SteveIves** [comment]
OK. I'm not sure who you are or how to contact you directly, so how about you email me at ***@***.******@***.***> and give me an idea of your availability Monday and Tuesday? I'll send you a meeting invite.

Steve

From: SledgeEC ***@***.***>
Sent: Friday, November 18, 2022 6:51 PM
To: Synergex/HarmonyCore ***@***.***>
Cc: Steve Ives ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [Synergex/HarmonyCore] Authentication via custom code (Issue #296)


That would be great. I had a couple other questions I needed some direction on and was already planning on trying to make an appointment.

-
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSynergex%2FHarmonyCore%2Fissues%2F296%23issuecomment-1320764455&data=05%7C01%7Csteve.ives%40synergex.com%7Cc83dd920f21444b2039508dac9d8ee69%7Cf3ba08220f7241fcbc3b2f77b0cb52bd%7C0%7C0%7C638044230822860032%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=P9ZLc4iqgttUQs%2FH0U4I7fPvyNXnNeVF3TVtwj0o2LU%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAHUZIBRSB3ZS2DGB7T3OTDWJA6CLANCNFSM6AAAAAASE7LTLQ&data=05%7C01%7Csteve.ives%40synergex.com%7Cc83dd920f21444b2039508dac9d8ee69%7Cf3ba08220f7241fcbc3b2f77b0cb52bd%7C0%7C0%7C638044230822860032%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0GxElEmM6D1JuHk%2BFe5FIXwgZ6cJUKxJIfEbEXVBBiU%3D&reserved=0>.
You are receiving this because you commented.Message ID: ***@***.******@***.***>>
CAUTION: This email originated from outside of Synergex. Please do not click links or open attachments from an unknown or suspicious sender.

**Comment by SledgeEC** [comment]
Good morning Steve,

I can be available anytime tomorrow after 10:30. I don’t think I can find time today, we had something pop up over the weekend and I was out of town so I need to deal with it.

This is Erik with Datavision, Inc. by the way. We did sign up for the DevPartner subscription again as part of this upgrade.

**Comment by SledgeEC** [comment]
For anybody else who may run up against this issue in the near future, there is an updated template to be released soon that needs to be used (ODataStartup.dbl). Once this has been replaced in the project and code regenerated it works correctly.
