### ISSUE TITLE
HarmonyCore cli issues

### ISSUE THREAD

**Issue by SledgeEC** [Synergex/HarmonyCore#318]
Good morning,

I am trying to add some records to my api and am getting a strange error- 'structure XXX is not assigned to file XXX'. I looked at the doc to see what I might be forgetting and can see the harmony core gui is now used to allow structures to be used in harmony core projects. However, when I try to run 'harmonycore gui' in the folder that has my solution, I get a NullReferenceException load error. The message within the gui says 'Failed to locate MSBuild path'.

Is there a registry var or something I am missing here to get this to work. I've tried researching what I might need to do but nothing I am finding is helpful. Thank you.

**Comment by hippiehunter** [comment]
Visual Studio 2022 has a bad habit of breaking your .net 6 sdk install. The easiest way I've found to solve this is to just reinstall the x64 .Net 6 sdk directly from Microsoft.

@SteveIves I think I understand what would make 'structure XXX is not assigned to *a* file' but I dont know why it would be referencing a specific file in the error message.

**Comment by SledgeEC** [comment]
I had tried reinstalling .net 7, which is what I had been using up to this point, and that did not help. Uninstalling 7 and reinstalling 6 did the trick. However, I am now running up against a number of other problems that prevent our api from functioning.

The issues seem to be related to the HarmonyCore cli not working as intended. One has an open bug and the other a closed bug but both are not working for me.

If I try to 'add structures' in the cli, it crashes. The bug report 307 describes it as related to using arrow keys to select the record, which matches my findings. I also tried not using the arrow keys and typing in the record name directly, and this also crashes. The inability to add the structures in the cli seems to be messing with the VS build and manual running of regen.

The other issue 308/315 is the import function. I have tried running this multiple times but it does not appear to do anything. Changes in the regen file it is supposed to pull from do not show in the cli.

 I followed the instructions for 'updating a harmony core solution' and 'updating to 3.1.90' and was able to eliminate the errors that popped up during build. However, nothing is working now. If I try to run our api I get 'unable to start debugging. startup project could not be launched. verify debug settings for startup project.' or I get an error saying path is not defined.

What do I need to do to get this to work? Is there a workaround for the cli or a way to revert my project and packages to the old way of adding structures directly in the regen? I was supposed to deploy the api to our clients server this week  and connect to their website but now nothing is working. I also tried creating an entirely new solution to try and avoid the issues caused by updating the code but the cli won't allow me to do anything so I am at a loss.

**Comment by hippiehunter** [comment]
do you have availability later today for a teams meeting to work through this?

**Comment by SledgeEC** [comment]
That would be great. I need to step out for a few but should be back by 3:30.

**Comment by SledgeEC** [comment]
Operating under your hypothesis, I decided to run the logicals and repos for both versions of our code. Both showed the incorrect file assignment. After I changed them, VS was able to run regen without issue. The question of how and why it was grabbing a different repo than the one the menu opens remains unanswered but can be ignored for now.

The other new issues I'm having are hopefully more straight forward...

I am able to run regen and all but one generates successfully, the postman development environment. I was able to import the odata info into postman and it shows the new apis for the records but I cannot successfully connect, I assume because the other file is not correct.

I am able to build in VS, but not to clean or rebuild. If I try either, I get one of two messages- 'clean/repair are not present in this project' or 'catastrophic failure- exception from HRESULT'. Since I can build this is not a priority but any obvious things I can try? Idk if this helps, but if I try to rebuild or clean and get the error, then try to build, it gives the same error and will not work until I exit and reopen VS.

If I try to run the project from VS, I get an error saying 'unable to start debugging. the startup project could not be launched. value cannot be null. parameter name: path 2.' or one that says 'unable to start debugging. the startup project could not be launched. verify debug settings for the startup project.' I get the same if I try to run without debug. Looking at the settings, I do not see anything obvious that is wrong or that I have changed in the past. Services.Host is set as the startup.

Since it wasn't working in VS, I tried to publish and run in IIS. I got the usual warnings but one error also showed up this time. It was for repository.synproj, error MSB4057- 'the target "publish" does not exist in the project'. I tried running it anyway and connecting with postman but get a 401 unauth even though I know the credentials match and everything else is the same as when it was working. Seems like this could be related to the issue I was having or our attempts to fix it since I hadn't seen this error before..?

The publishing and postman errors are the real priority for me. If you have ideas on how to fix the other problems I will try what you think will work but getting back to functioning is the immediate goal.

**Comment by SledgeEC** [comment]
Okay, that was able to knock out the error during publishing. Running in debug also worked after upgrading a couple of the NuGet packages, as well as rebuild and clean.

The last hurdle is the development environment file for postman which errors out during regen. My postman tests are getting 401. Even though I can see in debug that the username and password match, it drops down to return unauth. I can try to publish this to the client's IIS and connect from their website just to see if it is working but it would be great to have the postman functionality.

**Comment by SteveIves** [comment]
I can work with you on that on Monday. Have a good weekend.

Steve Ives

On Mar 3, 2023, at 16:23, SledgeEC ***@***.***> wrote:

﻿

Okay, that was able to knock out the error during publishing. Running in debug also worked after upgrading a couple of the NuGet packages, as well as rebuild and clean.

The last hurdle is the development environment file for postman which errors out during regen. My postman tests are getting 401. Even though I can see in debug that the username and password match, it drops down to return unauth. I can try to publish this to the client's IIS and connect from their website just to see if it is working but it would be great to have the postman functionality.

—
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSynergex%2FHarmonyCore%2Fissues%2F318%23issuecomment-1454206501&data=05%7C01%7Csteve.ives%40synergex.com%7Cc978d469b4d248f07bc808db1c35e912%7Cf3ba08220f7241fcbc3b2f77b0cb52bd%7C0%7C0%7C638134790109688754%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Cmoqm1WekxbLHMp8FOo%2B5tHDGiUXCca7UIpQ1sZm3G4%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAHUZIFKXQEAOVQ5MY64DVDW2JVN5ANCNFSM6AAAAAAVMIZMKE&data=05%7C01%7Csteve.ives%40synergex.com%7Cc978d469b4d248f07bc808db1c35e912%7Cf3ba08220f7241fcbc3b2f77b0cb52bd%7C0%7C0%7C638134790109702220%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=o9r8v0%2FazxWy0qzUl%2F6IBwGRag6YJ4ozbqMt7CXc90Y%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

CAUTION: This email originated from outside of Synergex. Please do not click links or open attachments from an unknown or suspicious sender.

**Comment by SledgeEC** [comment]
Just a quick update before our meeting since I was able to knock out the last couple errors I was getting.

The postman development environment error when running regen was fixed by changing the output option (-o . ^) to specify the solution directory.

The other error was caused by me not considering the .toLower() method when comparing usernames in AuthController.
