### ISSUE TITLE
Form - Field attributes and positions (Need advise)

### ISSUE THREAD

**Issue by GeethanjaliCP** [Synergex/HarmonyCore#369]
Currently we are migrating to Harmony Core.
We are not going to use Toolkit and planning to send all field attributes (Like Field name, Info line, Field data type etc) in JSON response. This is because, few details in forms will vary from customer to customer
and that is the reason we are sending all these details in JSON response.
To achieve the above we are hard coding all the details in the program.
Consider my form has 35 to 40 fields, and am sharing the below field properties for each field in the form.
Eg : 
			"FieldName": "Registration",
			"FieldId": "regn",
			"FieldDisable": 1,
			"FieldValue": "",
			"FieldDatatype": "Alpha",
			"FieldType": "Lookup",
			"FieldTypeList1": "",
			"FieldTypeList2": "",
			"FieldTypeList3": "",
			"FieldTypeList4": "",
			"FieldTypeList5": "",
			"FieldTypeList6": "",
			"FieldTypeList7": "",
			"FieldTypeList8": "",
			"FieldTypeList9": "",
			"FieldTypeList10": "",
			"FieldLimit": 7,
			"FieldPlaceholder": "Enter aircraft registration",
			"FieldFormat": "Uppercase",
			"FieldDescrKey": "",
			"FieldDescrValue": "",
			"DrillMethodType": "POST",
			"DrillMethod": "subroutine_name",
			"ChangeMethodType": "POST",
			"ChangeMethod": "subroutine_name"
First question :
We would like to understand like are we going on in a right way or is there any other alternative way?

Second question :
Coming to Field positions, Currently we have field positions in the .WSC file. Which would be the right way 
whether to send all field positions in json response.
or
Field positions should be maintained at the client end.
Which one would be appropriate? Please advise us.

**Comment by wh2005** [comment]
You should contact your Synergex account manager and setup a call with a Synergex subject matter expert. I don’t think you will be able to do what you are suggesting without a lot of work and it would probably impact performance.
Sent from my phone

On Aug 5, 2024, at 6:58 AM, GeethanjaliCP ***@***.***> wrote:

﻿

Currently we are migrating to Harmony Core.
We are not going to use Toolkit and planning to send all field attributes (Like Field name, Info line, Field data type etc) in JSON response. This is because, few details in forms will vary from customer to customer
and that is the reason we are sending all these details in JSON response.
To achieve the above we are hard coding all the details in the program.
Consider my form has 35 to 40 fields, and am sharing the below field properties for each field in the form.
Eg :
"FieldName": "Registration",
"FieldId": "regn",
"FieldDisable": 1,
"FieldValue": "",
"FieldDatatype": "Alpha",
"FieldType": "Lookup",
"FieldTypeList1": "",
"FieldTypeList2": "",
"FieldTypeList3": "",
"FieldTypeList4": "",
"FieldTypeList5": "",
"FieldTypeList6": "",
"FieldTypeList7": "",
"FieldTypeList8": "",
"FieldTypeList9": "",
"FieldTypeList10": "",
"FieldLimit": 7,
"FieldPlaceholder": "Enter aircraft registration",
"FieldFormat": "Uppercase",
"FieldDescrKey": "",
"FieldDescrValue": "",
"DrillMethodType": "POST",
"DrillMethod": "subroutine_name",
"ChangeMethodType": "POST",
"ChangeMethod": "subroutine_name"
First question :
We would like to understand like are we going on in a right way or is there any other alternative way?

Second question :
Coming to Field positions, Currently we have field positions in the .WSC file. Which would be the right way
whether to send all field positions in json response.
or
Field positions should be maintained at the client end.
Which one would be appropriate? Please advise us.
