### ISSUE TITLE
Trigger event when signalr disconnected?

### ISSUE THREAD

**Issue by shiblydangdang** [Synergex/HarmonyCore#370]
We store our license/connection information in a SQL table and the initial creation of a row is handled in the GetToken method and then subsequently in our Login method from the Web UI so we know who is logged in and is using a license.

Is there a way to trigger an event prior to the signalr connection being disconnected so that we can call a method from host.dbr?

If not, would we need to capture the close event on the browser and call a signalr routine before allowing the disconnect?

Hope this makes sense!

Thanks

**Comment by hippiehunter** [comment]
I posed your question to ChatGPT without specifying the language or anything about Harmony Core. Lets see if we can translate the answer into something that will work for you.

====================================

In SignalR, to handle client disconnection events, you can override the `OnDisconnectedAsync` method in your Hub class. This method is called whenever a client disconnects from the server. Here's an example:

```csharp
using Microsoft.AspNetCore.SignalR;
using System.Threading.Tasks;

public class MyHub : Hub
{
    public override async Task OnDisconnectedAsync(Exception exception)
    {
        // Handle the client disconnection here
        // You can log the disconnection, update user status, etc.

        await base.OnDisconnectedAsync(exception);
    }
}
```

### Steps to Register for a Client Disconnect Message:

1. **Create a Hub Class:**
   - Define a class that inherits from `Hub`.

2. **Override the `OnDisconnectedAsync` Method:**
   - Implement any logic that you want to execute when a client disconnects inside this method. For example, you might want to update a user's online status, log the disconnection, or notify other clients.

3. **Use the Hub in Your Application:**
   - Add the hub to your SignalR setup in the `Startup` class (for .NET Core 2.x/3.x) or `Program.cs` (for .NET 6/7).

Example of adding the Hub to your SignalR configuration:

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddSignalR();
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    app.UseRouting();

    app.UseEndpoints(endpoints =>
    {
        endpoints.MapHub<MyHub>("/myhub");
    });
}
```

When a client disconnects, the `OnDisconnectedAsync` method will be triggered, allowing you to perform any necessary cleanup or notifications.


=============================

The crucial part here is that you have a Hub of some sort. I don't have your source but I think the class that derives from Hub is likely generated but because its marked `partial` you can just add  something similar to this to a new file


```dbl
import AnyOtherImportantNamespacesHere
import Microsoft.AspNetCore.SignalR
import System.Threading.Tasks

namespace TheNamespaceOfYourGeneratedHubClassGoesHere
	public partial class TheNameOfYourGeneratedHubClassGoesHere extends Hub

		public override async method OnDisconnectedAsync, @Task 
			exception, @Exception
		proc
			;; Handle the client disconnection here
			;; You can log the disconnection, update user status, etc.
                        ;; Context.ConnectionId is available here to identify the client that disconnected
			await parent.OnDisconnectedAsync(exception)
		endmethod
	endclass
endnamespace
```

**Comment by shiblydangdang** [comment]
Thanks Jeff. Looks good to me. I'll give it a try asap.

**Comment by shiblydangdang** [comment]
Hi Jeff.

I finally had chance to have a look at this.

Our regen script already creates the override method as follows......

 ```
     ;;----------------------------------------------------------------------
      ;;; <summary>
      ;;; Executes when an existing connection is terminated
      ;;; </summary>
      ;;; <param name="ex"></param>
      ;;; <returns></returns>
      ;public override async method OnDisconnectedAsync, @Task
      ;    ex, @Exception
      ;proc
      ;    parent.OnDisconnectedAsync(ex)
      ;    data contextObject, @Object
      ;    if(Context.Items.TryGetValue("RPCContext", contextObject))
      ;    begin
      ;        data callContext = ^as(contextObject, @aspService)
      ;        if(callContext != ^null)
      ;        begin
      ;            _contextFactory.ReturnContext(callContext)
      ;        end
      ;    end
      ;endmethod

```
I've commented it out so that I can create the override method myself and it works fine.

Should I therefore just comment this method out in the SignalRHub.tpl file so that a future regen will generate this?

Thanks

**Comment by hippiehunter** [comment]
That looks like important code, I think you will want to merge your functionality into that .tpl file. If not you can use a partial method to hook the disconnect https://www.synergex.com/docs/#lrm/lrmChap4METHODENDMETHOD.htm?Highlight=partial If you go the partial method route we could incorporate that back into the default HarmonyCore templates.
